import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NextAuthProvider from '@/providers/next-auth-provider';
import Header from '@/components/header';
import Footer from '@/components/footer';
import Aside from '@/components/aside';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full">
            <NextAuthProvider>
                <body className={`${inter.className} h-full`}>
                    <Header />
                    <div className="app-page-wrapper h-full">
                        <main className="flex h-full">
                            <Aside />
                            <article className="grow">
                                {children}
                            </article>
                        </main>
                    </div>
                    <Footer />
                </body>
            </NextAuthProvider>
        </html>
    )
}
